# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreAnimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'ViewAnimator'

  target 'CoreAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoreAnimationUITests' do
    # Pods for testing
  end

end
